export const CHART_TYPES = [
  { id: 'bar', label: '棒グラフ' },
  { id: 'line', label: '折れ線' },
  { id: 'area', label: '面グラフ' },
  { id: 'scatter', label: '散布図' },
  { id: 'bubble', label: 'バブル' },
  { id: 'pie', label: '円グラフ' },
  { id: 'donut', label: 'ドーナツ' },
  { id: 'combination', label: '組み合わせ' },
  { id: 'box-plot', label: 'Box Plot' },
  { id: 'candlestick', label: 'Candlestick' },
  { id: 'ohlc', label: 'OHLC' },
  { id: 'heatmap', label: 'Heatmap' },
  { id: 'histogram', label: 'Histogram' },
  { id: 'nightingale', label: 'Nightingale' },
  { id: 'radar-line', label: 'Radar Line' },
  { id: 'radar-area', label: 'Radar Area' },
  { id: 'radial-column', label: 'Radial Column' },
  { id: 'radial-bar', label: 'Radial Bar' },
  { id: 'range-bar', label: 'Range Bar' },
  { id: 'range-area', label: 'Range Area' },
  { id: 'waterfall', label: 'Waterfall' },
  { id: 'sunburst', label: 'Sunburst' },
  { id: 'treemap', label: 'Treemap' },
  { id: 'sankey', label: 'Sankey' },
  { id: 'chord', label: 'Chord' },
  { id: 'multi-chord', label: 'Multi Chord' },
  { id: 'pentagon-chord', label: 'Pentagon Chord' },
  { id: 'funnel', label: 'Funnel' },
  { id: 'cone-funnel', label: 'Cone Funnel' },
  { id: 'pyramid', label: 'Pyramid' },
] as const

export type ChartTypeId = (typeof CHART_TYPES)[number]['id']
